# Generated by Django 3.2.14 on 2024-01-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0002_contry_contry_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='package_image')),
                ('number_of_days', models.IntegerField()),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('raings', models.IntegerField(blank=True, null=True)),
                ('number_of_rators', models.IntegerField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.destination')),
            ],
        ),
    ]
