# Generated by Django 3.2.14 on 2024-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0003_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='number_of_nights',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='number_of_persons',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
