# Generated by Django 3.2.14 on 2024-01-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0005_journey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='destination_include',
        ),
        migrations.AddField(
            model_name='journey',
            name='destination_include',
            field=models.ManyToManyField(blank=True, null=True, to='Destinations.Destination'),
        ),
    ]
