# Generated by Django 3.2.14 on 2024-01-15 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0007_auto_20240115_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guid_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.IntegerField()),
                ('Service', models.CharField(max_length=1000)),
                ('Guide_pic', models.FileField(upload_to='Guide_pic')),
                ('Destination_Near', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurants_Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Diat_and_menu', models.CharField(max_length=1000)),
                ('Restaurent_pic', models.FileField(upload_to='Rest_pic')),
                ('Destination_Near', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hotel_Name', models.CharField(max_length=255)),
                ('Room_Category', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Aminities', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Hotel_pic', models.FileField(upload_to='Rest_pic')),
                ('availability', models.BooleanField(default=True)),
                ('Destination_Near', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Destinations.destination')),
            ],
        ),
    ]
