# Generated by Django 3.2.14 on 2024-01-16 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Destinations', '0010_journybooking_packagebooking_tourguidebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journybooking',
            name='booker_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journybooking',
            name='booker_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journybooking',
            name='booker_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journybooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='booker_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='booker_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='booker_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagebooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tourguidebooking',
            name='booker_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourguidebooking',
            name='booker_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourguidebooking',
            name='booker_phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tourguidebooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_Name', models.CharField(max_length=255)),
                ('booker_phone', models.CharField(max_length=255)),
                ('booker_address', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destinations.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
