# Generated by Django 3.2.14 on 2024-01-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0011_auto_20240116_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='stop_beteween',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
