# Generated by Django 3.2.14 on 2024-01-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0012_journey_stop_beteween'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='epincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='spincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
