# Generated by Django 3.2.14 on 2024-01-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destinations', '0014_auto_20240118_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='stopbetween_mode',
            field=models.CharField(blank=True, choices=[('air', 'air'), ('train', 'train'), ('bus', 'bus'), ('other', 'other')], max_length=255, null=True),
        ),
    ]
